$(document).ready(function(){
    console.log("Content Loaded");

    $('.js-clickable').click(function(){
        $('#js-hidden').slideToggle();
        $('#js-visible').slideToggle();
    });
    $(".operator-click").click(function(){
        $("#operator-visible").slideToggle();
        $("#operator-hidden").slideToggle();
    })
    $(".variable-click").click(function(){
        $("#variable-visible").slideToggle();
        $("#variable-hidden").slideToggle();
    })
    $(".variable-n-click").click(function(){
        $("#variable-n-visible").slideToggle();
        $("#variable-n-hidden").slideToggle();
    })
    $(".functions-click").click(function(){
        $("#functions-visible").slideToggle();
        $("#functions-hidden").slideToggle();
    })
    $(".Methods-click").click(function(){
        $("#Methods-visible").slideToggle();
        $("#Methods-hidden").slideToggle();
    })
    $(".Arguments-click").click(function(){
        $("#Arguments-visible").slideToggle();
        $("#Arguments-hidden").slideToggle();
    })
    $(".Parameters-click").click(function(){
        $("#Parameters-visible").slideToggle();
        $("#Parameters-hidden").slideToggle();
    })
    $(".Return-click").click(function(){
        $("#Return-visible").slideToggle();
        $("#Return-hidden").slideToggle();
    })
    $(".Chaining-click").click(function(){
        $("#Chaining-visible").slideToggle();
        $("#Chaining-hidden").slideToggle();
    })
    $(".Strings-click").click(function(event){
        $("#Strings-visible").slideToggle();
        $("#Strings-hidden").slideToggle();
    })
    $(".Booleans-click").click(function(){
        $("#Booleans-visible").slideToggle();
        $("#Booleans-hidden").slideToggle();
    })
    $(".Undefined-click").click(function(){
        $("#Undefined-visible").slideToggle();
        $("#Undefined-hidden").slideToggle();
    })
    $(".NaN-click").click(function(){
        $("#NaN-visible").slideToggle();
        $("#NaN-hidden").slideToggle();
    })
    $(".Escape-click").click(function(){
        $("#Escape-visible").slideToggle();
        $("#Escape-hidden").slideToggle();
    })
    $(".Alert-click").click(function(){
        $("#Alert-visible").slideToggle();
        $("#Alert-hidden").slideToggle();
    })
    $(".Comments-click").click(function(){
        $("#Comments-visible").slideToggle();
        $("#Comments-hidden").slideToggle();
    })
    $(".jQuery-click").click(function(){
        $("#jQuery-visible").slideToggle();
        $("#jQuery-hidden").slideToggle();
    })
    $(".Attributes-click").click(function(){
        $("#Attributes-visible").slideToggle();
        $("#Attributes-hidden").slideToggle();
    })
    event.preventDefault();
});